In [1]:
import torch

In [2]:
x = torch.randn(3, requires_grad = True )
print(x)

tensor([-0.3885, -0.1626, -0.6140], requires_grad=True)


In [3]:
y = x+2 #graph is created
print(y)

tensor([1.6115, 1.8374, 1.3860], grad_fn=<AddBackward0>)


In [4]:
z = y*y*2
print(z)

tensor([5.1939, 6.7518, 3.8419], grad_fn=<MulBackward0>)


In [7]:
z = z.mean()
print(z)

tensor(5.2626, grad_fn=<MeanBackward0>)


In [8]:
z.backward() #dz/dx can only be created for scalar input


In [9]:
print(x.grad)

tensor([2.1487, 2.4498, 1.8480])


In [10]:
#v = torch.tensor([0.1, 1.0, 0.001], dtype = torch.float32)

### 3 ways to stop pytorch from calculating grad_fn

In [12]:
# x.requires_grad_(False)
# x.detach()
# with torch.no_grad()

tensor([-0.3885, -0.1626, -0.6140])


### training example

In [17]:
weights = torch.ones(4, requires_grad = True )
for epoch in range(2):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [19]:
#optimizer = torch.optim.SGD(weights, lr = 0.01) # stochastic gradient descent
#optimizer.step()
#optimizer.zero_grad()

In [21]:
#weights = torch.ones(4, requires_grad = True)
#z.backward()
#weights.grad.zero_()