# Tensor Basics

In [1]:
!pip install torch torchvision


In [2]:
import torch
import numpy as np

In [3]:
x = torch.empty(2,2,3)
print(x)

tensor([[[ 1.2612e-44,  0.0000e+00, -1.1035e+03],
         [ 3.0993e-41,  1.5835e-42,  4.3292e-41]],

        [[-1.1035e+03,  3.0993e-41,  1.5414e-44],
         [ 4.3292e-41,  0.0000e+00,  0.0000e+00]]])


In [4]:
x = torch.rand(2,2)
print(x)

tensor([[0.0922, 0.0551],
        [0.9590, 0.3364]])


In [5]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [6]:
x = torch.ones(2, dtype = torch.float16)

In [7]:
print(x.dtype)

torch.float16


In [8]:
print(x.size())

torch.Size([2])


In [9]:
x = torch.tensor([2.5 , 13], dtype = torch.float16)
print(x, x.dtype)

tensor([ 2.5000, 13.0000], dtype=torch.float16) torch.float16


## Operations

In [10]:
x = torch.rand(2)
y = torch.rand(2)

In [11]:
z = x+y
print(z)

tensor([1.2067, 0.2900])


In [12]:
y.add_(x)
print(y)

tensor([1.2067, 0.2900])


In [13]:
z = torch.sub(x,y)
z = torch.add(x,y)
z = torch.mul(x,y)

In [14]:
y.mul_(x)

tensor([1.2027, 0.0144])

In [15]:
z = x/y
z = torch.div(x,y)

## Access

In [16]:
torch.rand(5,3)

tensor([[0.4178, 0.6734, 0.1076],
        [0.5172, 0.0746, 0.2611],
        [0.0831, 0.0586, 0.5764],
        [0.0339, 0.7904, 0.0360],
        [0.6890, 0.2813, 0.1218]])

In [17]:
x = torch.rand(5,3)
print(x)
print(x[:,0]) #col number 1
print(x[0,:]) #row number 1

tensor([[0.7601, 0.6719, 0.0741],
        [0.8752, 0.1383, 0.3921],
        [0.4687, 0.6450, 0.4790],
        [0.0033, 0.4324, 0.0170],
        [0.0680, 0.3653, 0.4717]])
tensor([0.7601, 0.8752, 0.4687, 0.0033, 0.0680])
tensor([0.7601, 0.6719, 0.0741])


In [18]:
print(x[1,1].item())

0.1382942795753479


## Reshaping tensor

In [19]:
x = torch.rand(4,4)
y = x.view(16)
print(y)

tensor([0.7936, 0.2485, 0.7043, 0.0608, 0.0607, 0.2491, 0.6321, 0.9972, 0.3571,
        0.1082, 0.4096, 0.3690, 0.3907, 0.4326, 0.5826, 0.3019])


In [20]:
y = x.view(2,8)
print(y)

tensor([[0.7936, 0.2485, 0.7043, 0.0608, 0.0607, 0.2491, 0.6321, 0.9972],
        [0.3571, 0.1082, 0.4096, 0.3690, 0.3907, 0.4326, 0.5826, 0.3019]])


In [21]:
y = x.view(-1,8)
print(y)

tensor([[0.7936, 0.2485, 0.7043, 0.0608, 0.0607, 0.2491, 0.6321, 0.9972],
        [0.3571, 0.1082, 0.4096, 0.3690, 0.3907, 0.4326, 0.5826, 0.3019]])


## From torch to Numpy

In [22]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]


In [23]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [24]:
print(b) # a and b share the same memory location

[2. 2. 2. 2. 2.]


####  it's important to note that both the PyTorch tensor a and the NumPy array b will reference the same underlying data. This means that if you modify the data in the NumPy array b, the corresponding data in the PyTorch tensor a will also be modified, and vice versa.

In [26]:
x = torch.ones(5)
y = torch.ones(5)
z = x*y
z.numpy()

array([1., 1., 1., 1., 1.], dtype=float32)

In [ ]:
x = torch.ones(5, requires_grad=True) # when var will be optimized later